




CREATE PROC [DSQLT].[@GenerateDatabase] 
	 @Database sysname =null
	, @Print bit = 0
AS
exec DSQLT.[Execute] '@GenerateDatabase' ,@Database,@Print=@Print
RETURN 0
BEGIN
CREATE DATABASE [@1] ON  PRIMARY 
( NAME = N'@1', FILENAME = N'D:\Daten\SQL2008\MSSQL10.SQL2008\MSSQL\DATA\@1.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'@1_log', FILENAME = N'D:\Daten\SQL2008\MSSQL10.SQL2008\MSSQL\DATA\@1.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
ALTER DATABASE [@1] SET  READ_WRITE 
ALTER DATABASE [@1] SET RECOVERY FULL 
ALTER DATABASE [@1] SET  MULTI_USER 
ALTER DATABASE [@1] SET PAGE_VERIFY CHECKSUM  
ALTER DATABASE [@1] SET DB_CHAINING OFF 
END





